'use client';

import React from 'react';

import {
  HomeIcon,
  UserIcon,
  Cog6ToothIcon,
  BellIcon,
  ChartBarIcon,
  DocumentTextIcon,
  BookOpenIcon,
  AcademicCapIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  PlusIcon,
  MinusIcon,
  CheckIcon,
  XMarkIcon,
  MagnifyingGlassIcon,
  FunnelIcon,
  HeartIcon,
  StarIcon,
  ClockIcon,
  CalendarIcon,
  MapPinIcon,
  PhoneIcon,
  EnvelopeIcon,
  LockClosedIcon,
  EyeIcon,
  EyeSlashIcon,
  WifiIcon,
  SignalIcon,
  Battery50Icon,
  SunIcon,
  MoonIcon,
  SparklesIcon,
  FireIcon,
  BeakerIcon,
  CloudIcon,
  BoltIcon,
  DevicePhoneMobileIcon,
  ComputerDesktopIcon,
  ServerIcon,
  CircleStackIcon,
  ArrowPathIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  PencilIcon,
  TrashIcon,
  ClipboardDocumentIcon,
  ShareIcon,
  GiftIcon,
  ShoppingBagIcon,
  TagIcon,
  CurrencyDollarIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  QuestionMarkCircleIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  Bars3Icon,
  AdjustmentsHorizontalIcon,
  Squares2X2Icon,
  ListBulletIcon,
  PhotoIcon,
  CameraIcon,
  MicrophoneIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  ForwardIcon,
  BackwardIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  PaperAirplaneIcon,
  GlobeAltIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  UsersIcon,
  UserGroupIcon,
  IdentificationIcon,
  TicketIcon,
  TrophyIcon,
  GiftTopIcon,
} from '@heroicons/react/24/outline';

import {
  HeartIcon as HeartIconSolid,
  StarIcon as StarIconSolid,
  HomeIcon as HomeIconSolid,
  UserIcon as UserIconSolid,
  BellIcon as BellIconSolid,
  SunIcon as SunIconSolid,
  MoonIcon as MoonIconSolid,
  CheckCircleIcon,
  XCircleIcon,
  ExclamationTriangleIcon as ExclamationTriangleIconSolid,
  InformationCircleIcon as InformationCircleIconSolid,
} from '@heroicons/react/24/solid';

const iconMap = {
  home: HomeIcon,
  homeSolid: HomeIconSolid,
  user: UserIcon,
  userSolid: UserIconSolid,
  settings: Cog6ToothIcon,
  bell: BellIcon,
  bellSolid: BellIconSolid,
  chart: ChartBarIcon,
  document: DocumentTextIcon,
  book: BookOpenIcon,
  education: AcademicCapIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  plus: PlusIcon,
  minus: MinusIcon,
  check: CheckIcon,
  xmark: XMarkIcon,
  search: MagnifyingGlassIcon,
  filter: FunnelIcon,
  heart: HeartIcon,
  heartSolid: HeartIconSolid,
  star: StarIcon,
  starSolid: StarIconSolid,
  clock: ClockIcon,
  calendar: CalendarIcon,
  location: MapPinIcon,
  phone: PhoneIcon,
  email: EnvelopeIcon,
  lock: LockClosedIcon,
  eye: EyeIcon,
  eyeSlash: EyeSlashIcon,
  wifi: WifiIcon,
  signal: SignalIcon,
  battery: Battery50Icon,
  sun: SunIcon,
  sunSolid: SunIconSolid,
  moon: MoonIcon,
  moonSolid: MoonIconSolid,
  sparkles: SparklesIcon,
  fire: FireIcon,
  drop: BeakerIcon,
  cloud: CloudIcon,
  bolt: BoltIcon,
  deviceMobile: DevicePhoneMobileIcon,
  desktop: ComputerDesktopIcon,
  server: ServerIcon,
  database: CircleStackIcon,
  refresh: ArrowPathIcon,
  download: ArrowDownTrayIcon,
  upload: ArrowUpTrayIcon,
  edit: PencilIcon,
  trash: TrashIcon,
  clipboard: ClipboardDocumentIcon,
  share: ShareIcon,
  gift: GiftIcon,
  shoppingBag: ShoppingBagIcon,
  tag: TagIcon,
  currency: CurrencyDollarIcon,
  errorCircle: ExclamationCircleIcon,
  warning: ExclamationTriangleIcon,
  warningSolid: ExclamationTriangleIconSolid,
  info: InformationCircleIcon,
  infoSolid: InformationCircleIconSolid,
  question: QuestionMarkCircleIcon,
  chevronDown: ChevronDownIcon,
  chevronUp: ChevronUpIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  menu: Bars3Icon,
  sliders: AdjustmentsHorizontalIcon,
  grid: Squares2X2Icon,
  list: ListBulletIcon,
  photo: PhotoIcon,
  camera: CameraIcon,
  mic: MicrophoneIcon,
  play: PlayIcon,
  pause: PauseIcon,
  stop: StopIcon,
  forward: ForwardIcon,
  backward: BackwardIcon,
  volume: SpeakerWaveIcon,
  mute: SpeakerXMarkIcon,
  chat: ChatBubbleLeftRightIcon,
  message: ChatBubbleOvalLeftEllipsisIcon,
  send: PaperAirplaneIcon,
  globe: GlobeAltIcon,
  building: BuildingLibraryIcon,
  office: BuildingOffice2Icon,
  users: UsersIcon,
  userGroup: UserGroupIcon,
  id: IdentificationIcon,
  ticket: TicketIcon,
  trophy: TrophyIcon,
  giftTop: GiftTopIcon,
  success: CheckCircleIcon,
  error: XCircleIcon,
};

export default function Icon({
  name,
  size = 24,
  color = 'currentColor',
  className = '',
  ...props
}) {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  return (
    <IconComponent
      width={size}
      height={size}
      color={color}
      className={className}
      {...props}
    />
  );
}

export { iconMap };
